### ISSUE TITLE
Syriac script

### ISSUE THREAD

**Issue by rmaxton** [fihristorg/fihrist-mss#100]
I'm trying to copy Syriac script into Oxygen editor and it's only displaying as box-like symbols - do you know if there's a way to add new scripts? (I should say, it appears correctly when I apply the transformation scenario). Thanks!

**Comment by andrew-morrison** [comment]
The box-like symbols just mean the font being used to the display the text doesn't support those characters.

If you go to Options > Preferences, then expand Appearance and click on Fonts, you can change the Editor font. Depending on which version of Oxygen you are using, there should be a Sample box you can paste some Syriac into, and a checkbox to Show only the fonts that can render the sample text. If it isn't already selected, try Monospaced first.

**Comment by rmaxton** [comment]
Great, that was most helpful! Thanks.
