### ISSUE TITLE
Github log-in for Jeremy

### ISSUE THREAD

**Issue by yf227** [fihristorg/fihrist-mss#102]
Hi Andrew, can we please include Jeremy Penner <jsp61@cam.ac.uk> to the list of contributors? Jeremy has been working on the Cambridge Ethiopic manuscripts. Since Andrew has left, I wondered who else to contact. Many thanks.

**Comment by andrew-morrison** [comment]
You should be able to invite people yourself:

1. Go to https://github.com/orgs/fihristorg/people
2. If you are logged in, you'll see all the people in the Fihrist group.
3. Click the green "Invite member" button.
4. Enter the email address of the person and click "Invite".
5. When asked for their role, leave it on the default "Member" option.
6. Click "Send invitation".

GitHub will then send them an email notification. They have seven days to follow a link in the email to become a member. If they do so, they should then have the ability to commit and push changes to the fihrist-mss repository. If they don't have a GitHub account, it'll tell them how to get one. If they don't receive it, the email is probably in their junk mail folder.
