### ISSUE TITLE
Request for list of existing xml:id numbers for Manchester Persian manuscripts

### ISSUE THREAD

**Issue by ElizabethGow** [fihristorg/fihrist-mss#103]
Hi, 
I'm maintaining a list of the xml:id numbers associated with the University of Manchester manuscripts on Fihrist, so we can improve the way we link between records in Fihrist and the Manchester Digital Collections. 

I have a list of the new xml:id numbers allocated a while back (manuscript_13789-manuscript_26704), but no list/concordance which maps xml:id to shelfmark for the items already on Fihrist (most Persian MSS, all Syriac and Pashto MSS). It looks like the identifiers don't go in running number order, and I can't find a way to extract the information from Github. 

Please could you let me know if it is possible to generate a list of xml:id numbers matched to manuscript identifiers/filenames?

Many thanks
Elizabeth

**Comment by andrew-morrison** [comment]
Here is the list you requested:

[manchester_filenames_ids_and_shelfmarks_20210923.xlsx](https://github.com/fihristorg/fihrist-mss/files/7218538/manchester_filenames_ids_and_shelfmarks_20210923.xlsx)

Look in the method tab inside the spreadsheet for instructions if you ever need to re-run it yourself.

**Comment by ElizabethGow** [comment]
Thank you so much for doing this and so quickly!
Best wishes
Elizabeth

Elizabeth Gow l Part-time Manuscript Curator and Archivist l The John Rylands Research Institute and Library l The University of Manchester Library l The University of Manchester l 150 Deansgate l Manchester l M3 3EH l Tel +44 (0)161 2753541

Working hours: 9.00am-5.00pm, Thursday to Friday
