### ISSUE TITLE
Work ID merger

### ISSUE THREAD

**Issue by JakeBenson** [fihristorg/fihrist-mss#107]
Hi, @cookjools, I just found two entries for Kemalpaşazade's Nigaristan [here](https://www.fihrist.org.uk/catalog/work_20588) and [here](https://www.fihrist.org.uk/catalog/work_2837). Note that I just committed two records attached to the latter, although it looks like the former bears the new format? Thanks!

**Comment by yf227** [comment]
disambiguated these, thanks for pointing it out.
