### ISSUE TITLE
Small caps in author names don't properly display Turkish dotted i

### ISSUE THREAD

**Issue by kontovasBodleian** [fihristorg/fihrist-mss#119]
The default css setting on <a class="author"> elements sets _font-variant_ to _small-caps_. (This doesn't always display properly on all browsers, but it does in most Windows ones.) Unfortunately, this removes the dot from lower-case **i**, rendering it as **I**, which is problematic for Ottoman/Turkish names in Latin script, where **I~ı** and **İ~i** are two separate letters. Since _small-caps_ doesn't have great support across all browsers in all platforms anyway, perhaps we could do away with this setting?

![fihrist-dot-problem](https://user-images.githubusercontent.com/122795084/216633348-3a8d7820-82b5-43f5-be32-15b959394b6c.png)

**Comment by andrew-morrison** [comment]
I'm not a linguist, but I assume you mean there is a character in Turkish which represents a different sound to Latin i, but renders identically in small-caps, so it might confuse readers?

The use of small-caps is inherited from the [Oxford medieval catalogue](https://medieval.bodleian.ox.ac.uk/) where it is a style choice to make the author names stand out from the rest of the text. I can change Fihrist so authors aren't highlighted in this way, if @yf227 agrees.

**Comment by ek13** [comment]
My email seems to have dropped the thread.

Turkish has what we might call 2 Ii characters, one with and one without a dot in not lower and upper case.
I recall, perhaps incorrectly, that the original post noted one of the two was not displaying correctly.

https://en.wikipedia.org/wiki/Turkish_alphabet

**Comment by kontovasBodleian** [comment]
That is correct.

Basically, the Latin letter I~i in most languages has a dot in miniscule and no dot in majuscule form. In Turkish, however, there are two separate letters:

I~ı

and

İ~i

Note that in the latter, the majuscule is obligatorily dotted.

Since small-caps as a typological concept is based on non-Turkish languages, small-caps forms of the miniscule i are undotted in the vast majority fonts, meaning that all Turkish words with dotted i appear incorrectly.

The Turkish dotted capital İ is a known (and frustrating) issue in Turkish computing, but in Fihrist the only issue with it I have come across so far is this small-caps problem.


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by andrew-morrison** [comment]
Done.
