### ISSUE TITLE
Kursīnāmah

### ISSUE THREAD

**Issue by yf227** [fihristorg/fihrist-mss#122]
From an old issue: 
_Furthermore, the second work in Rylands Persian 882 is identical to BL Or 13255, albeit under an alternate title; however the latter bears [a different work ID](https://www.fihrist.org.uk/catalog/work_8596). Then it also appears that SOAS MS 46459 has a copy of this same work alone, again with yet [another different work ID.](https://www.fihrist.org.uk/catalog/work_10300). BTW, I just found that the Wellcome has another stand-alone volume of this as well, not yet in Fihrist, but it would be good to merge these together before they get around to adding it._

Can yo please check after tomorrow if this is now correct or has caused more issues? Thanks

**Comment by JakeBenson** [comment]
Rylands Persian 882 is identical to BL Or 13255 link to the same, but SOAS MS 46459 does not link with those.

**Comment by yf227** [comment]
done!
