### ISSUE TITLE
Rumi calendar

### ISSUE THREAD

**Issue by kontovasBodleian** [fihristorg/fihrist-mss#126]
Currently, the list of acceptable calendars doesn't include the Rumi calendar, used by the Ottoman Empire for various fiscal administrative functions from the 17th c. and officially starting with the Tanzimat in the 19th.

The Rumi calendar is effectively the same as the Julian, except that the month names are different and the new year starts in March as opposed to January -- that is, until 1 March 1917 (Gregorian) when they align the dates with the Gregorian instead. They abandon the calendar entirely 1926, but I am sure there will be some documents in our collections which use Rumi dates.

Should we add "#Rumi" as a valid option for dates?

(Also, while we're on the subject of dates: Is the correct format for "other" and "unknown" to use a hash in front of the words or no hash?)

**Comment by JakeBenson** [comment]
Thanks Niko! I heartily second this as we likely have documents in Persian MS 913 with Rumi dates (although Schmidt doesn't note them). While we're at it, we should ideally replace "#Hindu" with "#Vikram_Samvat", subcontinental #Fasli (seasonal) Mughal #Ilahi (frequently in inspection notations), and #Bangla, which is similar to Vikram Samvat. Also the Zoroastrians in Iran and India use different #Yazdigirdi, #Shahinshahi, and #Qadimi calendars. Also, I would love to figure out some formula for regnal dates. Perhaps 'role="calendar"' might work when we have "25th year ‘Ālamgīrī (reign of <persName role="calendar"> ‘Ālamgīr I</persName), or XXXX–XXXX CE)".  The Mughal regnal years all back-date to a Hijri month (Ramadan 1), so it can get pretty confusing, hence they have their own charts (see Hodiwala). However, including these calendars will necessarily expand the list of abbreviations...

**Comment by kontovasBodleian** [comment]
Wow, Indian calendars are a mess :-p

I guess it all depends on what we're using the date labels for functionally. AFAIK so far (correct me if I'm wrong, @andrew-morrison) the only script that employs the codes we use in the calendar attribute of date/origDate tags is the one that auto-generates AD/AH suffixes and puts a forwardslash between them if they're adjacent to one another. Everything else relies on tag attributes like when, notBefore, and notAfter, which are supposed to employ only Gregorian dates

If that's the only thing those calendar codes are used for in terms of processing, there's really no need to add more codes -- or indeed to have any other code than Gregorian. Since when, notBefore, and notAfter are already Gregorian-only, the other calendar data is only stored in the exclusively human readable textContent, no?

Are there reasons why we decided to do it the way we do it now? Are there legacy reasons why changing to a "one tag for all prose dates with Gregorian-only attributes" model would be bad for us?

**Comment by yf227** [comment]
Hi, the Gregorian calendar is the default. If you wanted to include other calendars beside the HQ, I wonder these can be added to the schema along with a few other values at other instances like script etc. I will need to discuss with Andrew if it can be done and if I can do it. 
The Gregorian date will remain the default and all other calendars are for display but could, if encoded,  serve as criteria for the selection of subsects, which would be sufficient.
