### ISSUE TITLE
collection-specific idno

### ISSUE THREAD

**Issue by kontovasBodleian** [fihristorg/fihrist-mss#134]
In most records, the first `<idno>` child of `<publicationStmt>` (with no `type` attribute) indicates something about either the collection or the project; newer Oxford records have "FIHRIST", older Oxford and Cambridge records have "OCIMCO", and several records have MARC organisation codes, as suggested in the old manual....

Many records, however, are lacking one of these, or have multiple codes, some of which seem to refer to the same thing. Here's the ones I've extracted:

<table>
   <tbody>
      <tr>
         <th>collection</th>
         <th>idno(s)</th>
         <th>issue(s)</th>
      </tr>
      <tr>
         <td rowspan='1'>british library</td>
         <td>BL</td>
         <td></td>
      </tr>
      <tr>
         <td rowspan='5'>cambridge university</td>
         <td>CulUK</td>
         <td>means same as UkCU & UKCU ?</td>
      </tr>
      <tr>
         <td>OCIMCO</td>
         <td></td>
      </tr>
      <tr>
         <td>UKCU</td>
         <td>var. of UkCU</td>
      </tr>
      <tr>
         <td>xyz</td>
         <td>boilerplate</td>
      </tr>
      <tr>
         <td>UkCU</td>
         <td></td>
      </tr>
      <tr>
         <td rowspan='1'>eton college windsor</td>
         <td>UkWE</td>
         <td></td>
      </tr>
      <tr>
         <td rowspan='1'>hertford college (university of oxford)</td>
         <td>FIHRIST</td>
         <td></td>
      </tr>
      <tr>
         <td rowspan='1'>jesus college (cambridge)</td>
         <td>UkCU-JE</td>
         <td></td>
      </tr>
      <tr>
         <td rowspan='1'>keble college (university of oxford)</td>
         <td>FIHRIST</td>
         <td></td>
      </tr>
      <tr>
         <td rowspan='1'>King's College Cambridge</td>
         <td>UkCU-KGS</td>
         <td></td>
      </tr>
      <tr>
         <td rowspan='1'>new college (university of oxford)</td>
         <td>ukoxunc</td>
         <td></td>
      </tr>
      <tr>
         <td rowspan='3'>oxford university</td>
         <td>FIHRIST</td>
         <td></td>
      </tr>
      <tr>
         <td>OCIMCO</td>
         <td></td>
      </tr>
      <tr>
         <td>UkOxU</td>
         <td></td>
      </tr>
      <tr>
         <td rowspan='1'>queen's college cambridge</td>
         <td>UkCU-QUE</td>
         <td></td>
      </tr>
      <tr>
         <td rowspan='1'>royal asiatic society of great britain and ireland</td>
         <td>UkLoRAS</td>
         <td></td>
      </tr>
      <tr>
         <td rowspan='3'>school of oriental and african studies</td>
         <td>SOAS</td>
         <td></td>
      </tr>
      <tr>
         <td>OCIMCO</td>
         <td></td>
      </tr>
      <tr>
         <td>UkLSOA</td>
         <td>means same as SOAS</td>
      </tr>
      <tr>
         <td rowspan='1'>st antony's college (oxford)</td>
         <td>FIHRIST</td>
         <td></td>
      </tr>
      <tr>
         <td rowspan='1'>the university of manchester</td>
         <td>UkMaJRU</td>
         <td></td>
      </tr>
      <tr>
         <td rowspan='2'>trinity college cambridge</td>
         <td>UkCU-TRI</td>
         <td></td>
      </tr>
      <tr>
         <td>????</td>
         <td>boilerplate</td>
      </tr>
      <tr>
         <td rowspan='1'>trinity college dublin, the university of dublin</td>
         <td>TCD</td>
         <td></td>
      </tr>
      <tr>
         <td rowspan='1'>trinity hall (cambridge)</td>
         <td>UkCU-TRH</td>
         <td></td>
      </tr>
      <tr>
         <td rowspan='1'>university of birmingham</td>
         <td>UkBU</td>
         <td></td>
      </tr>
      <tr>
         <td rowspan='1'>university of st andrews</td>
         <td>StSaUL</td>
         <td></td>
      </tr>
      <tr>
         <td rowspan='1'>wadham college (university of oxford)</td>
         <td>ukoxuwc</td>
         <td></td>
      </tr>
      <tr>
         <td rowspan='1'>wellcome trust</td>
         <td>UkLW</td>
         <td></td>
      </tr>
   </tbody>
</table>

Regularising these may not be desirable or important, but maybe @julian-cook-bl-uk or @andrew-morrison  could tell me what these codes are actually used for by the system -- if anything -- and anyone (@yf227, @awatson67, @JakeBenson ?) could chime in with suggestions as to how they should ideally look going forward? Are we still supposed to be using MARC organisation codes?

**Comment by andrew-morrison** [comment]
Fihrist has taken records from many sources, created over a long time span. In 2017-2018, certain changes were made to make them compatible with the use of authority files and the current web site. But those changes were deliberately kept minimal. The goal was not to make all records uniform in all respects. These IDs are an example of something that was left as they were because they have no effect on the display or indexing on the Fihrist web site. Likewise for class attributes and funder/publisher/principal author names. If the schema does not require them, you can safely leave them out of any new records you create, and ignore them when editing existing records.

**Comment by JakeBenson** [comment]
Manchester employs UkMaJRU an acronym for Manchester and Rylands for Special Collections records in both Fihrist and MDC.

**Comment by kontovasBodleian** [comment]
Thanks, both.

And thanks, @andrew-morrison, for the explanation. I'll mark this as resolved since the existing records don't require editing and take this into consideration moving forward!
