### ISSUE TITLE
Inconsistent *īyah/īyyah

### ISSUE THREAD

**Issue by JakeBenson** [fihristorg/fihrist-mss#135]
Just noting a number of romanized titles contain inconsistent *īyah / īyyah suffixes (both with and without the macron) across Arabic, Persian, and Turkish languages. Does ALA-LC stipulate the former for all of the languages we deal with? If so, it would be a pretty easy find/replace fix.

**Comment by kontovasBodleian** [comment]
In Ottoman, this ending is (according to LC and pronunciation) _-iye_ and should appear as such everyplace -- even in Arabic/Persian titles/excerpts in a Turkish context. (Incidentally, many records in Ottoman need to be re-written as they don't follow this latter, more general rule.)

LC guidelines are vague, but seem to indicate that the single _y_ should be used even in cases where the ی is explicitly marked with _teşdīd_ in the source material. Many transcribers will use _-iyye_ in these cases and these cases only, though this is not universal.

**Comment by kontovasBodleian** [comment]
Also, looking over the guidelines for Arabic, it seems LC wants _-īyah_. Presumably this is also what they recommend for Persian, given the general recommendation to defer to Arabic guidelines for Arabic elements in Persian.

**Comment by kontovasBodleian** [comment]
Yes, like I said: LC recommends -iye. The absence or presence of a t depends on the word.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
