### ISSUE TITLE
Chapter level work IDs in Persian MS 508

### ISSUE THREAD

**Issue by JakeBenson** [fihristorg/fihrist-mss#136]
Just noting that Rylands Persian MS 508 <https://www.fihrist.org.uk/catalog/work_7046> contains chapters with additional work IDs below. Could we structure this to show the relationship to the parent, like Qur'an Suras and Books of the Bible? If so, I see much more that could be done to consolidate work IDs, individual items in Khamsas and Haft Rangs, etc. Only in this case, should I resturcture these as 7046-1, 7046-2, etc? Can we automatically assign such new work IDs? It might make it easier for, say, when an isolated preface or book shows up to tag it as part of the overall work that way?

https://www.fihrist.org.uk/catalog/work_7047
https://www.fihrist.org.uk/catalog/work_7048
https://www.fihrist.org.uk/catalog/work_7049
https://www.fihrist.org.uk/catalog/work_7050
https://www.fihrist.org.uk/catalog/work_7051
https://www.fihrist.org.uk/catalog/work_7052
https://www.fihrist.org.uk/catalog/work_7053
https://www.fihrist.org.uk/catalog/work_7054
https://www.fihrist.org.uk/catalog/work_7055

**Comment by andrew-morrison** [comment]
It is not possible to change the work pages. And they are not intended for the purpose of explaining structures within particular instances of works. That is what the manuscript pages are for.

In this particular example, if 9 of those msItem are chapters within the first one, then they should:

- Be moved inside the first one, to establish the relationship in the structure of the TEI, and assert that the same author (and language, references, etc) applies to all. They would then be indented on the manuscript's page on the web site.
- Probably not have their own IDs. By removing the key attributes from their titles, it will unpublish their work pages, which are pretty pointless anyway, as they will only ever contain one link, to this one manuscript.

**Comment by yf227** [comment]
Many thanks, Andrew!

I will follow up with more discussion points on work ids  soon...

All the best

Yasmin

**Comment by JakeBenson** [comment]
Thank you, Andrew. In this case, that’s fine.

It would be good to develop some way to indicate relationships with standalone works compiled together with others into a larger parent work, such as a quintet or septet, much like we have isolated Qur’an suras and Bible books. Currently we have, say, separate work IDs for all Khamsa Quintets which contain 5 titles all with their own work IDs. Sometimes we have volumes with just 2 or 3 out of the five quintet titles too, which also have their own work IDs.

Ah, I see Yasmin replies. Reading my mind!

Jake

From: Andrew Morrison ***@***.***>
Date: Friday, 5 May 2023 at 09:19
To: fihristorg/fihrist-mss ***@***.***>
Cc: Jake Benson ***@***.***>, Author ***@***.***>
Subject: Re: [fihristorg/fihrist-mss] Chapter level work IDs in Persian MS 508 (Issue #136)

It is not possible to change the work pages. And they are not intended for the purpose of explaining structures within particular instances of works. That is what the manuscript pages are for.

In this particular example, if 9 of those msItem are chapters within the first one, then they should:

  *   Be moved inside the first one, to establish the relationship in the structure of the TEI, and assert that the same author (and language, references, etc) applies to all. They would then be indented on the manuscript's page on the web site.
  *   Probably not have their own IDs. By removing the key attributes from their titles, it will unpublish their work pages, which are pretty pointless anyway, as they will only ever contain one link, to this one manuscript.
