### ISSUE TITLE
broken link?

### ISSUE THREAD

**Issue by yf227** [fihristorg/fihrist-mss#141]
I am puzzled why this name entry doesn't show
https://www.fihrist.org.uk/catalog/person_f7899
 While there is an entry in the persons-base file
```
<person xml:id="person_f7899">
                    <persName type="display">Muḥammed bin Muṣṭafā Ḫasībzāde</persName>
                    <persName type="variant">محمد بن مصطفی حسیب زاده</persName>
                    <!-- ../collections/oxford%20university%2FMS_Sale_66.xml#MS_Sale_66 -->
 </person>
```

**Comment by kontovasBodleian** [comment]
Hello, Yasmin! I'm not sure exactly what you mean here. Could you elaborate? I'll try and see if maybe I've missed something.

**Comment by yf227** [comment]
It shows now, actually. May have been a matter of indexing.
