### ISSUE TITLE
default display of <locusGrp> in <msItem>

### ISSUE THREAD

**Issue by kontovasBodleian** [fihristorg/fihrist-mss#148]
I'm just going off the Fihrist preview at the moment, so I could be wrong, but it seems that our style sheet collapses multiple `<locus>` tags within a `<locusGrp>` into a single line, at least within `<msItem>`. Is this by design, or is this an artefact of the default display property of tags within `<msItem>`? If it's the latter, could we change this styling to render line breaks as line breaks between `<locus>` tags? Or should I just enter the `<locus>`'s directly into the `<msItem>` tag (which actually does display them on separate lines)?

**Comment by andrew-morrison** [comment]
There is nothing in the XSLT to specifically handle `locusGrp` elements. It is seldom used, and where it has been people appear to have added commas, or the word "and", inside the first `locus`, for example:

https://github.com/bodleian/medieval-mss/blob/6b584d6e1bb77b90d71321af5b6d3f3509bf0a01/collections/Christ_Church/Christ_Church_MS_105.xml#L74-L77

https://github.com/fihristorg/fihrist-mss/blob/2e1d15e91621855abf2745be828f560db454aa6d/collections/university%20of%20birmingham/Islamic_Arabic_322.xml#L97-L100

Rendering line breaks in the XML as line breaks in the HTML would create an inconsistency between what is significant whitespace and what isn't, and could be easily broken by someone applying, for example, Oxygen's Format and Indent tool to tidy-up the XML.

**Comment by kontovasBodleian** [comment]
Aha! Gotcha. I had tried putting a comma between the <locus> elements themselves, but <locusGrp> doesn't accept unembedded textContent. Putting the punctuation in the <locus> itself seems wrong to me for no good non-conceptual reason, but I'll think about whether doing that or just omitting the <locusGrp> altogether bothers me less :-)

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by andrew-morrison** [comment]
It is one of the problems with XML document formats: unless you initially develop the XSLT to deal with all possible usages, which is next to impossible with a schema as complex as TEI, then people will come up with workarounds that then limit the ability to subsequently augment the XSLT to handle them consistently. In this case, I could make it automatically add commas, but then you'd have double commas where people have already added them inside the locus elements. 

But the from and to attributes of the locus element provide a way to encode machine-readable values, so punctuation in the content of locus isn't a big issue.
