### ISSUE TITLE
msDesc/msIdentifier/idno as compulsory field in schema

### ISSUE THREAD

**Issue by eifionjones** [fihristorg/fihrist-mss#51]
Just wondering if the schema should enforce at least some text in titleStmt/title, as the website makes such important use of the field. Might save a lot of bad records being uploaded

**Comment by andrew-morrison** [comment]
Sounds reasonable. I'll add it to the list, and try to implement it before the training.

**Comment by andrew-morrison** [comment]
Unless I'm missing something, the website doesn't make use of `titleStmt/title`. The heading at the top of each manuscript comes from `msDesc/msIdentifier/idno` (with, on Fihrist, the sibling `repository` and `institution` elements added in brackets.)

Not that `titleStmt/title` isn't a good thing to include. In fact, it is required by the core TEI P5 schema.

So I've renamed this issue.

**Comment by eifionjones** [comment]
Ah! I must have got that wrong

I’ll amend the powerpoint, but lets keep title as a compulsory field as, as you say, it’s a TEI requirement!
Huw
