### ISSUE TITLE
facs attributes displaying in Wellcome records

### ISSUE THREAD

**Issue by amme2** [fihristorg/fihrist-mss#59]
e.g. https://www.fihrist.org.uk/catalog/manuscript_7732

They seem to be some kind of identifier for digitised images. Displaying in fihrist online for some elements and not others.

**Comment by andrew-morrison** [comment]
I can certainly hide those attributes so they don't appear on the web site.

As to their original purpose, it seems strange they were added to so many kinds of TEI elements: authors, titles, dates, even dimensions.

**Comment by amme2** [comment]
Agreed! I'll look back at the cataloguing guidelines from the time they were created, and see if I can figure out how they are intended to work. I'd definitely rather hide them than strip them out altogether at this point.

**Comment by amme2** [comment]
Ok, they are indeed image identifiers for this [legacy website](http://wamcp.bibalex.org/). If it's possible please, hiding them so they don't display on fihrist for the time being would be the best solution for now. We can then change them into identifiers for our current viewer when the whole set is revised.

**Comment by andrew-morrison** [comment]
Fix now on the production web site.
