### ISSUE TITLE
Manchester, John Rylands - numerous different persons associated with a single ID

### ISSUE THREAD

**Issue by sm2005** [fihristorg/fihrist-mss#63]
see the list of JR mss listed for person with id 90040229: https://www.fihrist.org.uk/catalog/person_90040229 
view the JR ms records on that list and it is clear what I mean (some do not even appear to contain a name with that ID yet they appear in the list of results)

**Comment by andrew-morrison** [comment]
It appears that, at some stage, a template was used to build some of these Manchester files, maybe others, which included the same author...
```
<author ref="http://viaf.org/viaf/90040229/" key="person_90040229"/>
```
...which then wasn't deleted when/if the work(s) were by unknown authors.

At least, that is the most likely explanation I can think of.

Someone needs to review these TEI files and remove this and anything else that may not be relevant.

**Comment by ElizabethGow** [comment]
Thanks Andrew
I’ll sort these out as soon as I can – just back from annual leave so it might take a little time!

Best wishes
Elizabeth

Elizabeth Gow l The University of Manchester l Tel +44 (0)161 2753541
elizabeth.gow@manchester.ac.uk<mailto:elizabeth.gow@manchester.ac.uk>

**Comment by andrew-morrison** [comment]
The web site has been updated with some changes made by Elizabeth yesterday. If you're happy with the results, please close this issue.

**Comment by ElizabethGow** [comment]
Thanks Andrew
I’ve just checked and realise that I missed the edit on Persian MS 60 (was distracted by its title which was completely wrong), but will sort this next week. The other remaining item is correct!

Elizabeth

Elizabeth Gow l The University of Manchester l Tel +44 (0)161 2753541
elizabeth.gow@manchester.ac.uk<mailto:elizabeth.gow@manchester.ac.uk>

**Comment by ElizabethGow** [comment]
I have corrected all the records so am closing this issue.
