### ISSUE TITLE
Preview problem - msdesc2html.xsl not found 

### ISSUE THREAD

**Issue by ElizabethGow** [fihristorg/fihrist-mss#65]
Hello
I was successfully using the previewManuscript.xsl transformation recently (I think it was last week), but now Oxygen cannot complete the transformation. I get the following error message: 

System ID: https://raw.githubusercontent.com/fihristorg/fihrist-mss/master/processing/previewManuscript.xsl
Scenario: Fihrist Arabic - github
XML file: P:\C_Manuscript cataloguing etc\Fihrist github\Arabic\Arabic MSS 1-20\JRL_ArabicMS1.xml
XSL file: https://raw.githubusercontent.com/fihristorg/fihrist-mss/master/processing/previewManuscript.xsl
Engine name: Saxon-PE 9.8.0.12
Severity: error
Description: I/O error reported by XML parser processing https://raw.githubusercontent.com/fihristorg/fihrist-mss/master/processing/lib/msdesc2html.xsl: 404 Not Found for: https://raw.githubusercontent.com/fihristorg/fihrist-mss/master/processing/lib/msdesc2html.xsl

I hope this is a problem that can be easily rectified (and indeed I may be doing something wrong - please let me know!).
Many thanks
Elizabeth

**Comment by andrew-morrison** [comment]
Sorry, this was caused by a change I made about a week before going on holiday. I thought I had tested it, but not completely. I'll fix it today.

**Comment by andrew-morrison** [comment]
This should now be working again. Open GitHub Desktop, pull the latest changes, and then try previewing again in Oxygen.
