### ISSUE TITLE
Unsupported calendars

### ISSUE THREAD

**Issue by ElizabethGow** [fihristorg/fihrist-mss#74]
Hello
I've recently uploaded records for two of our Persian manuscripts which are dated using the Samvat calendar. I encoded these as follows:

`<origDate calendar="#Hindu" when="1845">Samvat 1902 (1845 CE)</origDate>`

However, despite the "when" attribute being given in the Gregorian calendar, the century isn't being indexed properly, and they come up as "Date in unsupported calendar".

Is there a fix for this other than just using calendar="#Gregorian"?

Thanks
Elizabeth

**Edited so XML code is displayed

**Comment by andrew-morrison** [comment]
The problem with unsupported calendars is that it isn't clear whether their `when` attributes had been converted to the Gregorian calendar, as per the TEI standard. About half the Hijri-qamari ones hadn't, so I batch converted those, but I didn't have time to research and convert all the less common calendars ("Coptic-EoM", "Alexandrian", "AM", "Other", etc.)

There were only five `origDate` elements in all the Fihrist collections which had a `calendar` of "#Hindu", now seven with your new ones, and they all appear to have the same roughly 57-year offset as your example, so I've added "#Hindu" to the list of supported calendars. And re-indexed, so your new records should now be included in the "19th Century" option in the Century filter.
