### ISSUE TITLE
Setting up local fihrist repository

### ISSUE THREAD

**Issue by rmaxton** [fihristorg/fihrist-mss#79]
Hi Andrew,

I have recently got a new laptop and need to reinstall GitHub to my desktop. I have followed the instructions as before, but every time I go to clone the Fihrist repository on GitHub desktop, it just comes up with all these error messages and doesn't work.
Do you have any ideas at all what I can do?!

Many thanks,
Rosie

**Comment by andrew-morrison** [comment]
What are the error messages?

**Comment by rmaxton** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/41272244/58341754-e2d60c80-7e46-11e9-91c8-4bd1a9626fff.png)

**Comment by andrew-morrison** [comment]
Try the following:

 * Follow the instructions to at the bottom of [this page](https://support.microsoft.com/en-gb/help/4028544/windows-10-turn-windows-defender-firewall-on-or-off) to "Allow an app through the firewall", then clone fihrist-mss again.
 * If that doesn't work, follow the instructions on the same page to "Turn Windows Defender Firewall off", clone fihrist-mss again, then re-enable the firewall afterwards. Then see if you commit and push changes.
 * Clone again while connected to a different network.
 * Try again on another day.

**Comment by rmaxton** [comment]
Hi Andrew,
Many thanks for all the help. After trying the steps above, the cloning managed to work when I simply tried again on a different wifi network! 
Just one other question though - with regards to configuring the transformation scenario on XML editor, could you please remind me which options to select? I remember you showed us at the workshop, but I can't find it in the guidelines...

**Comment by andrew-morrison** [comment]
I have written some instructions here:

https://github.com/fihristorg/fihrist-mss/wiki/Configuring-Oxygen-to-Preview-TEI-in-the-Fihrist-Stylesheet

**Comment by rmaxton** [comment]
Thank you so much for this - that's extremely helpful!
