### ISSUE TITLE
Empty "key" value for <title>

### ISSUE THREAD

**Issue by rmaxton** [fihristorg/fihrist-mss#87]
Hello! I'm sorry if I missed this from yesterday's meeting, but just wanted to check: when adding a new title, should "variant" types have the empty key value too, or is it just the "uniform" type? E.g.

  <title xml:lang="ar-Latn-x-lc" key=""  type="uniform">al-Mukhtaṣar al-Shāfī ʿalá matn
                al-Kāfī</title>
              <title xml:lang="ar-Latn-x-lc"  type="variant">Ḥāshiyah ʿalá matn al-Kāfī fī ʿilmay al-ʿarūḍ
                wa-al-qawāfī</title>

Thank you!!

**Comment by yf227** [comment]
Hi Rosie
Thanks for this.
If you have a work id, you can add the key to all variants in the record. If you are awaiting a work Id to be generated by the system first, do not add the key attribute to the variants as this will generate more than one work id for the same work.

Thanks again for reassuring yourself on this.
Best wishes
Yasmin

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Rosie Maxton ***@***.***>
Sent: Wednesday, March 24, 2021 8:50:55 AM
To: fihristorg/fihrist-mss ***@***.***>
Cc: Yasmin Faghihi ***@***.***>; Assign ***@***.***>
Subject: [fihristorg/fihrist-mss] Empty "key" value for <title> (#87)


Hello! I'm sorry if I missed this from yesterday's meeting, but just wanted to check: when adding a new title, should "variant" types have the empty key value too, or is it just the "uniform" type? E.g.

<title xml:lang="ar-Latn-x-lc" key="" type="uniform">al-Mukhtaṣar al-Shāfī ʿalá matn al-Kāfī</title> <title xml:lang="ar-Latn-x-lc" type="variant">Ḥāshiyah ʿalá matn al-Kāfī fī ʿilmay al-ʿarūḍ wa-al-qawāfī</title>

Thank you!!

**Comment by rmaxton** [comment]
Brilliant, understood. Many thanks for this, Yasmin!
Rosie
