### ISSUE TITLE
Configuring transformation scenario

### ISSUE THREAD

**Issue by rmaxton** [fihristorg/fihrist-mss#93]
Hello! 
I'm having trouble applying the transformation scenario on my files for preview and I think I need to reconfigure it. Are there any instructions on this as I can't remember how I previously did so?
Many thanks!
Rosie

**Comment by andrew-morrison** [comment]
Try these instructions:

https://github.com/fihristorg/fihrist-mss/wiki/Configuring-Oxygen-to-Preview-TEI-in-the-Fihrist-Stylesheet

If that doesn't work, re-open this issue and provide details of how and when it doesn't work for you.
