### ISSUE TITLE
Duplicate work

### ISSUE THREAD

**Issue by JakeBenson** [fihristorg/fihrist-mss#95]
This record for https://www.fihrist.org.uk/catalog/work_7183 contains two different titles. 
Two Rylands manuscripts, [Persian MS 447](https://www.fihrist.org.uk/catalog/manuscript_6944) and [559](https://www.fihrist.org.uk/catalog/manuscript_7056) are the biography of Shaykh Ali Hazin.
However, Cambridge Or. 1635 and Rylands 610 are a different work attributed to the same author (unclear whether  authentic) on animals variously titled Saydiyah, Risalah-i Saydiyah, etc., which appears to be this work:
https://www.fihrist.org.uk/catalog/work_11074, which displays the correct author information.

**Comment by yf227** [comment]
All moved now! Thanks for pointing it out.
