### ISSUE TITLE
we need more role codes

### ISSUE THREAD

**Issue by yf227** [fihristorg/fihrist-mss#97]
I think we need more role codes as Jake is finding lot's of names in the MSs
In this list https://www.loc.gov/marc/relators/relaterm.html I found 
Honoree [hnr]
A person, family, or organization honored by a work or item (e.g., the honoree of a festschrift, a person to whom a copy is presented), which maybe also used for all those Mughal rulers as in https://www.fihrist.org.uk/catalog/manuscript_14673 
We may also add a new one for the kings of renal years...can we do that?
Can I edit the file in the WIKI?

**Comment by andrew-morrison** [comment]
All the MARC relator codes are supported, including `hnr` for Honoree.

The codes listed on the [Role codes wiki page](https://github.com/fihristorg/fihrist-mss/wiki/Role-codes) are just the ones that @cookjools used or invented a year ago. Listing all MARC relator codes there would be unhelpful as there are a lot of codes that'll never be relevant to Fihrist (e.g. `vdg` for Videographer or `cpc` for Copyright claimant).

Feel free to add `hnr` to the wiki page.

**Comment by ek13** [comment]
Some of the Role codes
<https://github.com/fihristorg/fihrist-mss/wiki/Role-codes> in MARC would
require either:

   1. Prospectively: Petitioning of the MARC Development Office -- this
   would be done through the British Library.  If not directly accepted by LC,
   it would go to a MARBI (MARC control board), which holds bi-annual
   meetings, the next in January.
   or
   2. Currently (role code review):
      - Use of the nearest Relator term + an explanatory note OR use a more
      appropriate field
         - 'cataloguer' data would go into
         https://www.loc.gov/marc/bibliographic/bd883.html (though I think
         most place it in a local 9xx field) - should FIHRIST TEI be amended?
         cataloguer is not inherent to the work (doesn't describe the
work), it's
         applied data (about describing the work) - if sent to MARBI, they'll
         probably tell us that it belongs elsewhere.
         - 'continuator' is difficult.  a book cataloguer might use the
         relator term 'bibliographic antecedent'
         - 'glossator' if I understand.  a book cataloguer (or maybe just
         an American) would use the relator 'annotator' with a note of
explanation
         if necessary.
         - 'reviser' would be the relator 'corrector'
         - 'super-commentator' use 'commentator' with a note indicating
         role as super-commentator
         - 'super-glossator' use 'annotator' with a note indicting role as
         super-glossator


Erich Kesse
Collections Care & Digitisation
SOAS, University of London
Russell Square, London WC1H 0XG
Telephone +44 (0) 20 7898 4798
https://www.soas.ac.uk/library/
*SOAS Digital Collections <https://digital.soas.ac.uk/>*

**Comment by ek13** [comment]
An after-thought.  How do we handle provenance?

the LC relator code for this would be 'former owner' [fmo] when ownership
is certain or 'associated name' [asn] of uncertain association; sometimes
an associated name is indicated by a 'signer' [sgn], e.g., 'from the
library of', or, when accompanied by a statement usually of transmission
('from dearest daddy' or 'with compliments') 'inscriber' [ins]

Erich Kesse
Collections Care & Digitisation
SOAS, University of London
Russell Square, London WC1H 0XG
Telephone +44 (0) 20 7898 4798
https://www.soas.ac.uk/library/
*SOAS Digital Collections <https://digital.soas.ac.uk/>*

**Comment by yf227** [comment]
Hi Erich, so far we are doing OK with the MARC relator terms, I will just have to add a few to the Wiki.
As for provenance, yes, we are doing it as you suggested. 
Thanks for your reply,
